---

- name: Generate Buildbot master and worker credentials
  hosts: localhost
  become: no
  tags:
    - buildbot
  tasks:
    - name: Generate Buildbot TLS certificates
      import_role:
        name: buildbot-tls-certificates
      tags:
        - buildbot-tls

- name: Install/Setup Docker images and containers on Daedalus
  hosts: daedalus
  become: true
  become_user: root
  become_method: sudo
  tags:
    - buildbot
    - buildbot-master
  vars:
    known_hosts: "{{ gitlab_keys.stdout_lines | sort | join('\n') }}"
  tasks:
    - name: Scan Gitlab ssh keys
      command: ssh-keyscan {{gitlab_hostname}}
      register: gitlab_keys
      changed_when: false
      tags:
        - always

    - name: Build and start the Buildbot master container
      import_role:
        name: buildbot-master

- name: Setup Buildbot worker system
  hosts: builder
  become: true
  become_user: root
  become_method: sudo
  tags:
    - buildbot
    - buildbot-worker
  vars:
    asset_host: "https://{{nexus_hostname}}/repository"
    asset_user: "buildbot"
    asset_password: "{{nexus_buildbot_password}}"
    asset_downloads:   "{{ asset_host }}/download"
    asset_orphans:     "{{ asset_host }}/orphans"
    asset_debian:      "{{ asset_host }}/debian"
    asset_sourceforge: "{{ asset_host }}/sourceforge"
    asset_gnu:         "{{ asset_host }}/gnu"
    asset_xorg:        "{{ asset_host }}/xorg"
    asset_kernel:      "{{ asset_host }}/kernel/linux"
    asset_pypi:        "{{ asset_host }}/pypi"
    known_hosts:       "{{ gitlab_keys.stdout_lines | sort | join('\n') }}"
    ptk_archive_uri:   "{{ asset_downloads }}/610-009981-023_SW_PTK_5.9_Client_RevA.tar"
  tasks:
    - name: Scan Gitlab ssh keys
      command: ssh-keyscan {{gitlab_hostname}}
      register: gitlab_keys
      changed_when: false
      tags:
        - always

    - name: Build and start the NTEL container
      import_role:
        name: buildbot-worker-ntel
      vars:
        buildbot_worker_hostdir_config: '{{ buildbot_worker_ntel_hostdir_config }}'
        buildbot_worker_name: '{{ buildbot_worker_ntel }}'
        buildbot_worker_passwd: '{{ buildbot_worker_ntel_passwd }}'
        buildbot_worker_tlsca: '{{ buildbot_ca_pem }}'
        buildbot_worker_tlskey: '{{ buildbot_worker_ntel_tlskey }}'
        buildbot_worker_tlspem: '{{ buildbot_worker_ntel_tlspem }}'

      tags:
        - buildbot-worker-ntel

    - name: Build and start the PTXdist container
      import_role:
        name: buildbot-worker-ptxdist
      vars:
        buildbot_worker_hostdir_config: '{{ buildbot_worker_ptxdist_hostdir_config }}'
        buildbot_worker_name: '{{ buildbot_worker_ptxdist }}'
        buildbot_worker_passwd: '{{ buildbot_worker_ptxdist_passwd }}'
        buildbot_worker_tlsca: '{{ buildbot_ca_pem }}'
        buildbot_worker_tlskey: '{{ buildbot_worker_ptxdist_tlskey }}'
        buildbot_worker_tlspem: '{{ buildbot_worker_ptxdist_tlspem }}'
      tags:
        - buildbot-worker-ptxdist
