---
- name: Generate ssl certs for MySQL server and clients
  hosts: localhost
  tags: ssl_certificates
  tasks:
  # Generate ansibleremote ssh keys
  - name: Create directory
    file:
      mode: 0700
      path: "credentials/ansibleremote"
      state: directory
  - name: ssh key generate
    openssh_keypair:
      mode: 0600
      path: "credentials/ansibleremote/root"
      size: 4096
      state: present
      type: rsa
  - name: ssh key generate
    openssh_keypair:
      mode: 0600
      path: "credentials/ansibleremote/user"
      size: 4096
      state: present
      type: rsa

  # Generate buildbot ssh keys
  - name: Create directory
    file:
      mode: 0700
      path: "credentials/buildbot"
      state: directory
  - name: ssh key generate
    openssh_keypair:
      mode: 0600
      path: "credentials/buildbot/master_rsa"
      size: 4096
      state: present
      type: rsa
  - name: ssh key generate
    openssh_keypair:
      mode: 0600
      path: "credentials/buildbot/worker_ntel_rsa"
      size: 4096
      state: present
      type: rsa
  - name: ssh key generate
    openssh_keypair:
      mode: 0600
      path: "credentials/buildbot/worker_ptxdist_rsa"
      size: 4096
      state: present
      type: rsa

  # Generate Certificate Authority
  - name: Makes sure the local dir for ssl files exists
    file:
      mode: 0700
      path: 'credentials/buildsystem/ssl'
      state: directory

  - name: Generate ca key
    openssl_privatekey:
      path: 'credentials/buildsystem/ssl/ca-key.pem'
      size: 8192
      type: RSA
      state: present

  - name: Generate ca.csr
    openssl_csr:
      path: 'credentials/buildsystem/ssl/ca.csr'
      privatekey_path: 'credentials/buildsystem/ssl/ca-key.pem'
      basic_constraints:
      - "CA:TRUE"
      CN: cert_auth_ts.novatech-llc.com
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      state: present

  - name: Generate ca.pem
    openssl_certificate:
      csr_path: 'credentials/buildsystem/ssl/ca.csr'
      path: 'credentials/buildsystem/ssl/ca.pem'
      privatekey_path: 'credentials/buildsystem/ssl/ca-key.pem'
      provider: selfsigned
      selfsigned_not_after: '+3650d'

  - name: Generate server key
    openssl_privatekey:
      path: 'credentials/buildsystem/ssl/server-key.pem'
      size: 8192
      type: RSA
      state: present

  - name: Generate server req
    openssl_csr:
      path: 'credentials/buildsystem/ssl/server-req.csr'
      privatekey_path: 'credentials/buildsystem/ssl/server-key.pem'
      CN: buildsystem.novatech-llc.com
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      state: present

  - name: Generate server cert
    openssl_certificate:
      csr_path: 'credentials/buildsystem/ssl/server-req.csr'
      path: 'credentials/buildsystem/ssl/server-cert.pem'
      privatekey_path: 'credentials/buildsystem/ssl/server-key.pem'
      provider: ownca
      ownca_not_after: "+3650d"
      ownca_path: 'credentials/buildsystem/ssl/ca.pem'
      ownca_privatekey_path: 'credentials/buildsystem/ssl/ca-key.pem'

  - name: Generate replication client key
    openssl_privatekey:
      path: 'credentials/buildsystem/ssl/replication_user_client-key.pem'
      size: 8192
      type: RSA
      state: present

  - name: Generate replication client req
    openssl_csr:
      path: 'credentials/buildsystem/ssl/replication_user_client-req.csr'
      privatekey_path: 'credentials/buildsystem/ssl/replication_user_client-key.pem'
      CN: www.novatech-llc.com
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      state: present

  - name: Generate replication client cert
    openssl_certificate:
      csr_path: 'credentials/buildsystem/ssl/replication_user_client-req.csr'
      path: 'credentials/buildsystem/ssl/replication_user_client-cert.pem'
      privatekey_path: 'credentials/buildsystem/ssl/replication_user_client-key.pem'
      provider: ownca
      ownca_not_after: '+3650d'
      ownca_path: 'credentials/buildsystem/ssl/ca.pem'
      ownca_privatekey_path: 'credentials/buildsystem/ssl/ca-key.pem'

  - name: Generate update_user client key
    openssl_privatekey:
      path: 'credentials/buildsystem/ssl/update_user_client-key.pem'
      size: 8192
      type: RSA
      state: present

  - name: Generate update_user client req
    openssl_csr:
      path: 'credentials/buildsystem/ssl/update_user_client-req.csr'
      privatekey_path: 'credentials/buildsystem/ssl/update_user_client-key.pem'
      CN: www.novatech-llc.com
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      state: present

  - name: Generate update_user client cert
    openssl_certificate:
      csr_path: 'credentials/buildsystem/ssl/update_user_client-req.csr'
      path: 'credentials/buildsystem/ssl/update_user_client-cert.pem'
      privatekey_path: 'credentials/buildsystem/ssl/update_user_client-key.pem'
      provider: ownca
      ownca_not_after: '+3650d'
      ownca_path: 'credentials/buildsystem/ssl/ca.pem'
      ownca_privatekey_path: 'credentials/buildsystem/ssl/ca-key.pem'

  # Generate haproxy dhparam
  - name: Makes sure the local dir for ssl files exists
    file:
      mode: 0700
      path: 'credentials/haproxy'
      state: directory

  - name: Generate haproxy dhparam
    openssl_dhparam:
      mode: 0600
      path: 'credentials/haproxy/dhparam.pem'
      size: 4096
      state: present
