- name: Install/Setup Docker images and containers on daedalus
  hosts: daedalus
  remote_user: ansibleremote
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: Build and start the Grafana Docker container
    import_role:
      name: grafana
    tags:
      - grafana_container
