---
# This playbook deploys the whole application stack in this site.

- name: Bacula
  hosts: bacula
  user: '{{ remote_user_username }}'
  sudo: true
  roles:
  - role: mariadb
    vars:
    - mariadb_open_firewall: true
    - mariadb_remote_root_access: false
  - role: bacula-director
    vars:
    - bacula_director_backup_vms: 'freeipa-centos7'
  - role: bacula-storage
  - role: bacula-client
  - role: bacula-console
  - role: bacula-catalog

- name: Virtual machines
  hosts: virtual-machine-hosts
  user: '{{ remote_user_username }}'
  sudo: true
  roles:
  - role: libvirt-lvmpool
  - role: libvirt-vm
    vars:
    - vm_name: freeipa-centos7
    - vm_pool: virtstorage
    - vm_vol: freeipa-centos7-vol
    - vm_capacity: 40000M
    - vm_image: freeipa-centos7_vda.img
    - vm_start: True

- name: Install/Setup Docker images and containers
  hosts: docker-hosts
  user: '{{ remote_user_username }}'
  sudo: true
  roles:
  - name: Build base images that are not on Docker Hub
    role: docker-build-base-image
    tags:
    - base_images
  - name: Build and start the SVN Docker container
    role: docker-svn
    vars:
    - svn_repos: 'ddio novatech NCD_Release'
    tags:
    - svn_container
  - name: Build and start the GitLab Docker container
    role: docker-gitlab
    vars:
    - gitlab_db_user: novatech
    tags:
    - gitlab_container
  - name: Build and start the MediaWIKI Docker container
    role: docker-mediawiki
    vars:
    - wiki_db_user: novatech
    tags:
    - wiki_container

- name: Bacula backup scripts
  hosts: bacula
  user: '{{ remote_user_username }}'
  sudo: true
  roles:
  - role: bacula-backup-scripts
