---
# This playbook deploys the whole application stack in this site.

- name: Bacula
  hosts: bacula
  user: ansibleremote
  sudo: true

  roles:
    - { role: mariadb, mariadb_open_firewall: true, mariadb_remote_root_access: false }
    - { role: bacula-director, bacula_director_backup_vms: 'freeipa-centos7' }
    - { role: bacula-storage }
    - { role: bacula-client }
    - { role: bacula-console }
    - { role: bacula-catalog }


- name: Virtual machines
  hosts: virtual-machine-hosts
  user: ansibleremote
  sudo: true
    - { role: libvirt-lvmpool }
    - { role: libvirt-vm,
                vm_name: freeipa-centos7,
                vm_pool: virtstorage,
                vm_vol: freeipa-centos7-vol,
                vm_capacity: 40000M,
                vm_image: freeipa-centos7_vda.img,
                vm_start: True }


- name: install/setup Docker images and containers
  hosts: docker-hosts
  user: ansibleremote
  sudo: true

  roles:
  - name: Build base images that are not on Docker Hub
    role: docker-build-base-image
    tags:
    - base_images

  - name: Build and start the SVN Docker container
    role: docker-svn
    svn_repos: 'ddio novatech NCD_Release'
    tags:
    - svn_container

  - name: Build and start the MediaWIKI Docker container
    role: docker-mediawiki
    wiki_db_user: novatech
    tags:
    - wiki_container

  - name: Build and start the GitLab Docker container
    role: docker-gitlab
    gitlab_db_user: novatech
    tags:
    - gitlab_container
