---
bacula_director_password: '{{ bacula_director_password_vault }}'
bacula_email_password: '{{ bacula_email_password_vault }}'
bacula_monitor_password: '{{ bacula_monitor_password_vault }}'
mariadb_bacula_password: '{{ mariadb_bacula_password_vault }}'
mariadb_root_password: '{{ mariadb_root_password_vault }}'
