---
# tasks file for buildbot-master

# This will generate passwords for these accounts.
- name: Check conditions
  assert:
    that:
    - buildbot_master_sshkey is defined

- name: Create buildbot data volume
  docker_volume:
    name: '{{ data_volume }}'

- name: Create config directory
  file:
    path: "{{ config_hostdir }}"
    state: directory

- name: Populate config files
  copy:
    src: "{{ item }}"
    dest: "{{ config_hostdir }}/{{ item | basename }}"
    group: '{{ buildbot_uid }}'
    owner: '{{ buildbot_uid }}'
    mode: "u=rw,g=,o="
    unsafe_writes: yes
  register: configs
  loop:
    - novatech.py
    - '{{ buildbot_master_sshkey }}'

- name: Populate config templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ config_hostdir }}/{{ item }}"
    group: '{{ buildbot_uid }}'
    owner: '{{ buildbot_uid }}'
    mode: "u=rw,g=,o="
    unsafe_writes: yes
  register: templates
  loop:
    - master.cfg
    - buildbot.tac
    - known_hosts

- name: Create credential directory
  file:
    path: '{{ config_hostdir }}/ssl'
    state: directory

- name: Populate credential files
  copy:
    src: '{{ item.src }}'
    dest: "{{ item.dest }}"
    group: '{{ buildbot_uid }}'
    owner: '{{ buildbot_uid }}'
    mode: "u=rw,g=,o="
    unsafe_writes: yes
  register: credentials
  loop:
    - src: '{{ buildbot_sshkey }}'
      dest: '{{ config_hostdir }}/{{ buildbot_sshkey | basename }}'
    - src: '{{ buildbot_tlsca }}'
      dest: '{{ config_hostdir }}/ssl/ca.pem'
    - src: '{{ buildbot_tlskey }}'
      dest: '{{ config_hostdir }}/ssl/server.key'
    - src: '{{ buildbot_tlspem }}'
      dest: '{{ config_hostdir }}/ssl/server.pem'

- name: Create image source directory
  file:
    path: "{{ image_dir }}"
    state: directory

- name: Deploy image source
  synchronize:
    archive: yes
    checksum: yes
    compress: yes
    delete: yes
    src: docker/
    dest: '{{ image_dir }}/'
  register: deploy_source

- name: Create buildbot master image
  docker_image:
    build:
      args: '{{ image_args }}'
      path: '{{ image_dir }}'
      pull: yes
    name: '{{ image_name }}'
    source: build
    tag: '{{ docker_image_tag }}'
    force_source: "{{ deploy_source.changed }}"

- name: Start buildbot container
  docker_container:
    comparisons: {'*': strict}
    env: '{{ container_env }}'
    hostname: '{{ container_hostname }}'
    image: '{{ image_name }}:{{ docker_image_tag }}'
    name: '{{ container_name }}'
    networks: '{{ container_networks }}'
    ports: '{{ container_port_args }}'
    restart: '{{
      configs.changed
      or templates.changed
      or deploy_source.changed }}'
    restart_policy: '{{ docker_restart_policy }}'
    state: started
    volumes: '{{ container_volumes }}'
    working_dir: '{{ container_workdir }}'
