- delegate_to: localhost
  become: no
  block:
  - name: Makes sure the local dir for ssl files exists
    file:
      mode: 0700
      path: '{{ buildbot_master_tlskey | dirname }}'
      state: directory

  - name: Generate server key
    openssl_privatekey:
      path: '{{ buildbot_master_tlskey }}'
      size: 8192
      type: RSA
      state: present
    register: server_key

  - name: Generate server req
    openssl_csr:
      path: '{{ buildbot_master_tlscsr }}'
      privatekey_path: '{{ buildbot_master_tlskey }}'
      CN: '{{ container_hostname }}'
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      state: present
    when: server_key.changed

  - name: Generate server cert
    openssl_certificate:
      csr_path: '{{ buildbot_master_tlscsr }}'
      path: '{{ buildbot_master_tlspem }}'
      privatekey_path: '{{ buildbot_master_tlskey }}'
      provider: ownca
      ownca_not_after: "+3650d"
      ownca_path: '{{ buildbot_ca_pem }}'
      ownca_privatekey_path: '{{ buildbot_ca_key }}'
    when: server_key.changed

  - name: Generate Diffie-Hellman Parameters
    openssl_dhparam:
      path: '{{ buildbot_master_dhparam }}'
      size: 4096
      state: present
    when: server_key.changed

- name: Create certificate directory on target
  file:
    path: '{{ config_hostdir }}/ssl'
    state: directory

- name: Copy certificates and keys to target
  copy:
    src: '{{ item }}'
    dest: '{{ config_hostdir }}/ssl/'
  loop:
  - '{{ buildbot_ca_pem }}'
  - '{{ buildbot_master_dhparam }}'
  - '{{ buildbot_master_tlskey }}'
  - '{{ buildbot_master_tlspem }}'
