---
- name: Install/setup Bacula Director
  yum: name={{ item }} state=present
  with_items:
    - bacula-director
- name: Copy Bacula Director Config
  copy: src=bacula-dir.conf dest={{ bacula_director_config_dir }}/bacula-dir.conf
          owner=bacula group=bacula mode=0640 backup=yes
- name: Use libbaccats-mysql
  command: alternatives --set libbaccats.so /usr/lib64/libbaccats-mysql.so
- name: Check if bacula mysql database exists
  command: mysql -u root -e "SHOW DATABASES;"
  register: databases
- include: mariadb_setup.yml
  when: databases.stdout.find('bacula') == -1
- name: Test Bacula Director configuration
  command: /usr/sbin/bacula-dir -t -c {{ bacula_director_config_dir }}/bacula-dir.conf
- name: Enable and start Bacula Director
  service: name=bacula-dir enabled=yes state=started
