---
# file: roles/docker-mediawiki/tasks/main.yaml

# *****************************************************************************
# Setup the directory where the backup and restore is to take place

- name: backup dir
  file:
    state: directory
    path: '{{ wiki_docker_backup_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no
    setype: svirt_sandbox_file_t

- name: restore dir
  file:
    state: directory
    path: '{{ host_wiki_docker_restore_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no
    setype: svirt_sandbox_file_t

- name: docker_container.conf dir
  file:
    state: directory
    path: '{{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
    recurse: no

# *****************************************************************************
# update the Docker restore config

- name: make config.sh
  template:
    src: config.sh.j2
    dest: '{{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}/config.sh'
    backup: yes
    owner: root
    group: tape
    mode: 'u=rw,g=r,o='

- name: copy script
  command: 'cp --verbose --update --backup=numbered {{ docker_projects_dir }}/docker-mediawiki/mediawiki.sh {{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}'

- name: exists - state file
  stat:
    path: '{{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}/restore.date.txt'
    get_checksum: False
    get_md5: False
  register: st_mediawiki_restore

# *****************************************************************************
# Update or make the image.

- name: build image
  docker_build:
    image_name: '{{ wiki_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    dockerfile_dir: '{{ docker_projects_dir }}/docker-mediawiki'

# *****************************************************************************
# Create the data volumes

- name: data-volume container (mediwiki)
  docker_datavolume:
    image_name: '{{ wiki_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    data_volume_container_name: '{{ wiki_dv_name }}'

- name: data-volume container (mysql)
  docker_datavolume:
    image_name: '{{ wiki_db_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    data_volume_container_name: '{{ wiki_db_dv_name }}'

- name: stop prev container (mysql)
  docker:
    image: '{{ wiki_db_image_name }}'
    name: '{{ wiki_db_container_name }}'
    state: stopped

- name: initial populate (mysql)
  docker_db_init:
    image_name: '{{ wiki_db_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    container_name: '{{ wiki_db_dv_name }}_init_db'
    data_volume_container_name: '{{ wiki_db_dv_name }}'
    database_name: wikidb
    database_user: '{{ wiki_db_user }}'
    database_password: '{{ wiki_db_password | quote }}'
    database_root_password: '{{ wiki_db_root_password | quote }}'

# *****************************************************************************
# Start the data container running

- name: start container (mysql)
  docker_run:
    container_name: '{{ wiki_db_container_name }}'
    docker_run_arguments: '--volumes-from {{ wiki_db_dv_name }} {{ wiki_db_image_name }}:{{ docker_image_tag }}'

- name: start container (mediwiki)
  docker_run:
    container_name: '{{ wiki_container_name }}'
    docker_run_arguments: '{{ container_port_map.wiki.port_args }} --link {{ openldap_container_name }}:wiki_ldap --link {{ wiki_db_container_name }}:wiki_db --volumes-from {{ openssl_dv_name }} --volumes-from {{ wiki_dv_name }} --env WIKI_HOSTNAME={{ container_addr_map.wiki.hostname }} {{ wiki_image_name }}:{{ docker_image_tag }}'

# *****************************************************************************
# restore?

- include: restore.yml
  when: st_mediawiki_restore.stat.exists == False
