---
# file: roles/docker-common/tasks/main.yaml

- name: install yum package python-docker
  yum:
    name: python-docker
    state: present
  when: ansible_os_family == "RedHat"

- name: Install docker-py (1.0.0)
  pip: name=docker-py version=1.0.0
  when: ansible_os_family != "RedHat"

- name: restores base dir
  file:
    state: directory
    path: '{{ docker_restore_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no

- name: backups base dir
  file:
    state: directory
    path: '{{ docker_backup_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no

- name: base docker_container.conf dir
  file:
    state: directory
    path: '{{ docker_restore_config_base_dir }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: docker projects base directory
  file:
    state: directory
    path: '{{ docker_projects_dir }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: checkout git repositories
  git:
    repo: '{{ item.repo }}'
    dest: '{{ docker_projects_dir }}/{{ item.name }}'
    clone: yes
    recursive: yes
    update: yes
  with_items: docker_projects
  tags:
    - docker_repositories
