---
# file: roles/docker-common/tasks/main.yaml

- name: Create the docker group
  group:
    name: docker
    system: yes

- name: restart docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- include: ip_addr.yml
- include: packages.yml
- include: sshd_settings.yml

- name: restores base dir
  file:
    state: directory
    path: '{{ docker_restore_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no

- name: base docker_container.conf dir
  file:
    state: directory
    path: '{{ docker_restore_config_base_dir }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: docker projects base directory
  file:
    state: directory
    path: '{{ docker_projects_dir }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: checkout git repositories
  git:
    repo: '{{ item.repo }}'
    dest: '{{ docker_projects_dir }}/{{ item.name }}'
    clone: yes
    recursive: yes
    update: yes
  with_items: docker_projects
  tags:
    - docker_repositories

- name: Check if baculavirt selinux module exists
  stat:
    path: /etc/selinux/targeted/modules/active/modules/dockervirt.pp
  register: dockervirt_pp

- include: selinux-virt-policy.yml
  when: (dockervirt_pp.stat.exists is defined) and (dockervirt_pp.stat.exists == false)
