---

- name: Directory for backup scripts
  file:
    path: /usr/libexec/bacula/
    state: directory

- name: Create before_backup script
  template:
    src: before_backup.j2
    dest: /usr/libexec/bacula/before_backup
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'

- name: Create after_backup script
  template:
    src: after_backup.j2
    dest: /usr/libexec/bacula/after_backup
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
