---
# file: roles/docker-svn/tasks/main.yaml

# *****************************************************************************
# Setup the directory where the backup and restore is to take place

- name: backup dir
  file:
    state: directory
    path: '{{ svn_docker_backup_dir }}'
    owner: root
    group: root
    mode: 0755
    recurse: yes
    setype: svirt_sandbox_file_t

- name: restore dir
  file:
    state: directory
    path: '{{ host_svn_docker_restore_dir }}'
    owner: root
    group: root
    mode: 0755
    recurse: yes
    setype: svirt_sandbox_file_t

- name: docker_container.conf dir
  file:
    state: directory
    path: '{{ docker_restore_config_base_dir }}/{{ svn_dv_name }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

# *****************************************************************************
# update the Docker restore config

- name: exists - state file
  stat:
    path: '{{ docker_restore_config_base_dir }}/{{ svn_dv_name }}/restore.date.txt'
    get_checksum: False
    get_md5: False
  register: st_svn_restore

# *****************************************************************************
# Update or make the image.

- name: build image
  docker_build:
    image_name: '{{ svn_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    dockerfile_dir: '{{ docker_projects_dir }}/docker-svn'

# *****************************************************************************
# Create the data volumes

- name: data-volume container
  docker_datavolume:
    image_name: '{{ svn_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    data_volume_container_name: '{{ svn_dv_name }}'

# *****************************************************************************
# Start the data container running

- name: start container
  docker_run:
    container_name: '{{ svn_container_name }}'
    docker_run_arguments: '{{ svn_docker_port_mapping }} --link {{ openldap_container_name }}:ldap --volumes-from {{ openssl_dv_name }} --volumes-from {{ svn_dv_name }} --env SVN_HOSTNAME={{ svn_hostname }} {{ svn_image_name }}:{{ docker_image_tag }}'

# *****************************************************************************
# restore?

- include: restore.yml
  when: st_svn_restore.stat.exists == False
