---
- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb
- name: Enable and start MariaDB service
  service: name=mariadb enabled=yes state=started
- name: Check previous installation
  stat: path={{ mariadb_client_config }}
  register: cfg
- include: initial_config.yml
  when: cfg.stat.exists is defined and cfg.stat.exists == false
- name: Open the firewall
  firewalld: service=mysql permanent=true state=enabled
  when: mariadb_open_firewall
