- name: Create temp directory for policy creation
  command: mktemp -d /tmp/ansible-bacula-director.XXXXXXXX
  register: docker_tmp_dir

- name: Copy dockervirt type enforcement file
  copy:
    src: dockervirt.te
    dest: '{{ docker_tmp_dir.stdout }}/dockervirt.te'
    owner: root
    group: root
    mode: 0640

- name: Run checkmodule on dockervirt.te
  command: /usr/bin/checkmodule -M -m -o dockervirt.mod dockervirt.te
  args:
    chdir: '{{ docker_tmp_dir.stdout }}'

- name: Build dockervirt module
  command: /usr/bin/semodule_package -o dockervirt.pp -m dockervirt.mod
  args:
    chdir: '{{ docker_tmp_dir.stdout }}'

- name: Install dockervirt module
  command: /usr/sbin/semodule -i dockervirt.pp
  args:
    chdir: '{{ docker_tmp_dir.stdout }}'

- name: Delete temp directory
  file:
    path: '{{ docker_tmp_dir.stdout }}'
    state: absent
