---
- name: Check preconditions
  assert:
    that:
    - bacula_director_password is defined
    - bacula_monitor_password is defined
- name: Install/setup Bacula Storage
  yum:
    name:
    - bacula-mysql-9.4.4-1.el7
    state: present

- name: Create configuration directory
  file:
    path: '{{ bacula_storage_config_dir }}'
    owner: bacula
    group: bacula
    seuser: system_u
    serole: object_r
    setype: bacula_etc_t
    state: directory

- name: Configure Bacula Storage
  template:
    src: bacula-sd.conf.j2
    dest: '{{ bacula_storage_config_dir }}/bacula-sd.conf'
    owner: bacula
    group: bacula
    mode: 0640
  notify: "restart bacula-sd"

- name: Test Bacula Storage configuration
  command: |
    {{ bacula_install_bindir}}/bacula-sd -t
    -c {{ bacula_storage_config_dir }}/bacula-sd.conf
  changed_when: false

- name: Create Storage location
  file:
    path: '{{ bacula_storage_device_archive_device }}'
    owner: bacula
    group: bacula
    seuser: system_u
    serole: object_r
    setype: bacula_store_t
    state: directory
  when: bacula_storage_device_type == "File"

# *****************************************************************************
# Install selinux policies

- import_tasks: selinux-tape-policy.yml

- name: Enable and start Bacula Storage
  service:
    name: bacula-sd
    enabled: yes
    state: started
  register: bacula_storage_service
