---

# The hostname passed as an envirnment variable into the container
wiki_ip_addr: '127.0.0.1'
wiki_hostname: wiki.example.com
wiki_port_args:
  - '80'
  - '443'

# database usernames and passwords
wiki_db_user: novatech

# must pass in the following variables
# wiki_db_root_password: ''
# wiki_db_password: ''

# the name of the image being duilt and used for the container
wiki_image_repo: https://github.com/novatechweb/docker-mediawiki.git
wiki_image_name: '{{ docker_registry_username }}/wiki'
wiki_db_image_name: 'mysql:5'

# the name of the container being started
wiki_container_name: '{{ docker_name_prefix }}wiki'

# the name of the container being started
wiki_db_container_name: '{{ docker_name_prefix }}wiki_db'

# the name of the data-volume used by the container
wiki_dv_name: '{{ docker_name_prefix }}wiki_DV'

# the name of the mysql data-volume used by the mediawiki container
wiki_db_dv_name: '{{ docker_name_prefix }}wiki_db_DV'

# restore directories to temporarly store data being restored into docker containers
wiki_docker_backup_dir: '{{ docker_backup_dir }}/WIKI'
wiki_docker_restore_dir: '{{ bacula_dest }}{{ wiki_docker_backup_dir }}'

# Monitoring package for MediaWiki
wiki_monitor_image_name: 'lusotycoon/apache-exporter:v0.8.0'
wiki_monitor_container_name: '{{ docker_name_prefix }}wiki_monitor'
wiki_monitor_scrape_uri: "http://{{ wiki_container_name }}/server-status?auto" #URI to apache stub status page. (default "http://localhost/server-status/?auto")
wiki_monitor_telemetry_address: ":9117" #Address on which to expose metrics. (default ":9117")
wiki_monitor_telemetry_endpoint: "/metrics" #Path under which to expose metrics. (default "/metrics")

# files restored from tape
wiki_static_backup_file: '/mediawiki.tar'
wiki_database_backup_file: '/wikidb.sql'

# Network names
docker_network_frontend: 'frontend'

# the name of the sql database used by mediawiki
wiki_database_name: wikidb
