---
buildbot_version: '2.4.0'
buildbot_worker_port: '9989'
buildbot_worker_ntel: worker-ntel
buildbot_worker_ptxdist: worker-ptxdist

buildbot_master_connection_string: "\
  ssl\
  :port={{ buildbot_worker_port }}\
  :sslmethod=TLSv1_2_METHOD\
  :certKey=/etc/ssl/private/server.pem\
  :privateKey=/etc/ssl/private/server.key\
  :extraCertChain=/etc/ssl/private/ca.pem"

buildbot_worker_connection_string: "\
  tls\
  :host={{ buildbot_hostname }}\
  :port={{ buildbot_worker_port }}\
  :certificate=/etc/ssl/private/client.pem\
  :privateKey=/etc/ssl/private/client.key\
  :trustRoots=/etc/ssl/private"

buildbot_ca_creds: '{{ playbook_dir + "/credentials/buildbot-ca" }}'
buildbot_ca_dir: '{{ buildbot_ca_creds }}'
buildbot_ca_csr: '{{ buildbot_ca_creds + "/ca.csr" }}'
buildbot_ca_key: '{{ buildbot_ca_creds + "/ca.key" }}'
buildbot_ca_pem: '{{ buildbot_ca_creds + "/ca.pem" }}'
buildbot_ca_fields:
  common_name: cert_auth_ts.novatech-llc.com
  organization_name: NovaTech
  organizational_unit_name: Orion
  country_name: US
  state_or_province_name: Kansas
  locality_name: Lenexa

buildbot_client_certificates:
  - dir: '{{ buildbot_creds }}'
    csr: '{{ buildbot_tlscsr }}'
    key: '{{ buildbot_tlskey }}'
    pem: '{{ buildbot_tlspem }}'
    fields:
      CN: buildbot.novatech-llc.com
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
  - dir: '{{ buildbot_worker_ntel_creds }}'
    csr: '{{ buildbot_worker_ntel_tlscsr }}'
    key: '{{ buildbot_worker_ntel_tlskey }}'
    pem: '{{ buildbot_worker_ntel_tlspem }}'
    fields:
      CN: '{{ buildbot_worker_ntel }}'
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
  - dir: '{{ buildbot_worker_ptxdist_creds }}'
    csr: '{{ buildbot_worker_ptxdist_tlscsr }}'
    key: '{{ buildbot_worker_ptxdist_tlskey }}'
    pem: '{{ buildbot_worker_ptxdist_tlspem }}'
    fields:
      CN: buildbot-worker-ptxdist
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa

buildbot_creds: '{{ playbook_dir + "/credentials/buildbot" }}'
buildbot_sshkey: '{{ buildbot_creds }}/id_rsa'
buildbot_tlsca:  '{{ buildbot_ca_pem }}'
buildbot_tlscsr: '{{ buildbot_creds }}/server.csr'
buildbot_tlskey: '{{ buildbot_creds }}/server.key'
buildbot_tlspem: '{{ buildbot_creds }}/server.pem'

buildbot_email_password: '{{ lookup("password", buildbot_creds + "/buildbot@novatech-llc.com length=20 chars=ascii_letters,digits") }}'

buildbot_worker_network: '{{ docker_name_prefix }}workers'
buildbot_worker_networks:
  - name: '{{ buildbot_worker_network }}'
    aliases:
      - '{{ buildbot_worker_hostname }}'

buildbot_worker_ntel_creds: '{{ playbook_dir + "/credentials/buildbot-worker-ntel" }}'
buildbot_worker_ntel_passwd: '{{ lookup("password", buildbot_worker_ntel_creds + "/passwd length=20") }}'
buildbot_worker_ntel_sshkey: '{{ buildbot_worker_ntel_creds }}/id_rsa'
buildbot_worker_ntel_tlscsr: '{{ buildbot_worker_ntel_creds }}/client.csr'
buildbot_worker_ntel_tlskey: '{{ buildbot_worker_ntel_creds }}/client.key'
buildbot_worker_ntel_tlspem: '{{ buildbot_worker_ntel_creds }}/client.pem'

buildbot_worker_ptxdist_creds: '{{ playbook_dir + "/credentials/buildbot-worker-ptxdist" }}'
buildbot_worker_ptxdist_passwd: '{{ lookup("password", buildbot_worker_ptxdist_creds + "/passwd length=20") }}'
buildbot_worker_ptxdist_sshkey: '{{ buildbot_worker_ptxdist_creds }}/id_rsa'
buildbot_worker_ptxdist_tlscsr: '{{ buildbot_worker_ptxdist_creds }}/client.csr'
buildbot_worker_ptxdist_tlskey: '{{ buildbot_worker_ptxdist_creds }}/client.key'
buildbot_worker_ptxdist_tlspem: '{{ buildbot_worker_ptxdist_creds }}/client.pem'

buildbot_webhook_secret: '{{ lookup("password", buildbot_creds + "/webhook length=20") }}'

buildbot_master_worker_configs:
  - module: 'worker_ntel_morty'
    giturl: 'git@{{ gitlab_hostname }}:andrew.cooper/setup-scripts'
    branch: 'morty'
  - module: 'worker_ptxdist_master'
    giturl: 'git@{{ gitlab_hostname }}:andrew.cooper/workspace-ptxdist2'
    branch: 'master'
