---
# passwords
ansibleremote_gitlab_password: '{{ ansibleremote_gitlab_password_vault }}'
ansibleremote_user_private_key: '{{ ansibleremote_user_private_key_vault }}'
ansibleremote_user_public_key: '{{ ansibleremote_user_public_key_vault }}'
ansibleremote_root_private_key: '{{ ansibleremote_root_private_key_vault }}'
ansibleremote_root_public_key: '{{ ansibleremote_root_public_key_vault }}'
buildbot_admin_password: '{{ buildbot_admin_password_vault }}'
buildbot_email_password: '{{ buildbot_email_password_vault }}'
buildbot_gitlab_password: '{{ buildbot_gitlab_password_vault }}'
buildbot_master_ssh_private_key: '{{ buildbot_master_ssh_private_key_vault }}'
buildbot_master_ssh_public_key: '{{ buildbot_master_ssh_public_key_vault }}'
buildbot_worker_ntel_password: '{{ buildbot_worker_ntel_password_vault }}'
buildbot_worker_ntel_ssh_private_key: '{{ buildbot_worker_ntel_ssh_private_key_vault }}'
buildbot_worker_ntel_ssh_public_key: '{{ buildbot_worker_ntel_ssh_public_key_vault }}'
buildbot_worker_ptxdist_password: '{{ buildbot_worker_ptxdist_password_vault }}'
buildbot_worker_ptxdist_ssh_private_key: '{{ buildbot_worker_ptxdist_ssh_private_key_vault }}'
buildbot_worker_ptxdist_ssh_public_key: '{{ buildbot_worker_ptxdist_ssh_public_key_vault }}'
buildbot_webhook_secret: '{{ buildbot_webhook_secret_vault }}'
buildsystem_database_build_password: '{{ buildsystem_database_build_password_vault }}'
buildsystem_database_remote_update_password: '{{ buildsystem_database_remote_update_password_vault }}'
buildsystem_database_replication_password: '{{ buildsystem_database_replication_password_vault }}'
buildsystem_database_root_password: '{{ buildsystem_database_root_password_vault }}'
buildsystem_ddio_database_build_password: '{{ buildsystem_ddio_database_build_password_vault }}'
buildsystem_ddio_database_root_password: '{{ buildsystem_ddio_database_root_password_vault }}'
buildsystem_ssh_prod_user_password: '{{ buildsystem_ssh_prod_user_password_vault }}'
buildsystem_ssh_root_user_password: '{{ buildsystem_ssh_root_user_password_vault }}'
buildsystem_database_ssl_ca_csr: '{{ buildsystem_database_ssl_ca_csr_vault }}'
buildsystem_database_ssl_ca_key: '{{ buildsystem_database_ssl_ca_key_vault }}'
buildsystem_database_ssl_ca: '{{ buildsystem_database_ssl_ca_vault }}'
buildsystem_ssl_replication_user_client_cert: '{{ buildsystem_ssl_replication_user_client_cert_vault }}'
buildsystem_ssl_replication_user_client_key: '{{ buildsystem_ssl_replication_user_client_key_vault }}'
buildsystem_ssl_replication_user_client_csr: '{{ buildsystem_ssl_replication_user_client_csr_vault }}'
buildsystem_ssl_server_cert: '{{ buildsystem_ssl_server_cert_vault }}'
buildsystem_ssl_server_key: '{{ buildsystem_ssl_server_key_vault }}'
buildsystem_ssl_server_csr: '{{ buildsystem_ssl_server_csr_vault }}'
buildsystem_ssl_update_user_client_cert: '{{ buildsystem_ssl_update_user_client_cert_vault }}'
buildsystem_ssl_update_user_client_key: '{{ buildsystem_ssl_update_user_client_key_vault }}'
buildsystem_ssl_update_user_client_csr: '{{ buildsystem_ssl_update_user_client_csr_vault }}'
gitlab_buildbot_auth_id: '{{ gitlab_buildbot_auth_id_vault }}'
gitlab_buildbot_auth_secret: '{{ gitlab_buildbot_auth_secret_vault }}'
gitlab_buildbot_token: '{{ gitlab_buildbot_token_vault }}'
gitlab_email_password: '{{ gitlab_email_password_vault }}'
gitlab_root_password: '{{ gitlab_root_password_vault }}'
gitlab_root_private_token: '{{ gitlab_root_private_token_vault }}'
haproxy_stats_password: '{{ haproxy_stats_password_vault }}'
haproxy_dhparam_pem: '{{ haproxy_dhparam_pem_vault }}'
mantisbt_db_password: '{{ mantisbt_db_password_vault }}'
mantisbt_db_root_password: '{{ mantisbt_db_root_password_vault }}'
mantisbt_email_password: '{{ mantisbt_email_password_vault }}'
nexus_admin_password: '{{ nexus_admin_password_vault }}'
nexus_bacula_password: '{{ nexus_bacula_password_vault }}'
nexus_buildbot_password: '{{ nexus_buildbot_password_vault }}'
nexus_email_password: '{{ nexus_email_password_vault }}'
novatech_llc_com_ca_bundle_crt: '{{ novatech_llc_com_ca_bundle_crt_vault }}'
novatech_llc_com_csr: '{{ novatech_llc_com_csr_vault }}'
novatech_llc_com_key: '{{ novatech_llc_com_key_vault }}'
novatech_llc_com_star_crt: '{{ novatech_llc_com_star_crt_vault }}'
openldap_admin_password: '{{ openldap_admin_password_vault }}'
openldap_proxyagent_password: '{{ openldap_proxyagent_password_vault }}'
openldap_ansible_password: '{{ openldap_ansible_password_vault }}'
supportsite_database_root_password: '{{ supportsite_database_root_password_vault }}'
wiki_db_password: '{{ wiki_db_password_vault }}'
wiki_db_root_password: '{{ wiki_db_root_password_vault }}'
wiki_email_password: '{{ wiki_email_password_vault }}'
