---

exim4_hostname: "{{ production_role }}mail.novatech-llc.com"

# the name of the container being started
exim4_container_name: '{{ docker_name_prefix }}exim4'

# Data volume directory for the syslog data
exim4_syslog_datavolume_dir: '/var/log/docker_container/{{ exim4_container_name }}'
