nexus_version: 3.16.1
nexus_networks:
  - name: '{{ docker_network_frontend }}'
    aliases:
      - '{{ public_hostname }}'
nexus_host_docker: true
nexus_default_port: 8081

# Nexus Backup
nexus_docker_backup_dir: "{{ docker_backup_dir }}/NEXUS3"
nexus_docker_backup_archive: "{{ nexus_docker_backup_dir }}/nexus3.tar.gz"
nexus_backup_dir: '/var/nexus-backup'
nexus_backup_blob_filter:
  - permanent
# Shall we configure backup ?
nexus_backup_configure: true
# Backup time cron expression
nexus_backup_manual: true
# Shall we rotate backups ? No effect if nexus_backup_configure is false
nexus_backup_rotate: false
nexus_backup_keep_rotations: 1  # Keep 4 backup rotation by default (current + last 3)
nexus_backup_task_name: db and blobstores backup

nexus_email_server_enabled: true
nexus_email_server_host: "mail.novatech-llc.com"
nexus_email_server_port: 587
nexus_email_server_username: "wiki"
nexus_email_server_password: "{{ nexus_email_password }}"
nexus_email_from_address: "nexus@novatech-llc.com"
nexus_email_subject_prefix: "[NEXUS]"
nexus_email_tls_enabled: true
nexus_email_tls_required: true

nexus_ldap_realm: true
ldap_connections:
  - ldap_name: 'NovaTech LDAP' # used as a key to update the ldap config
    ldap_protocol: 'ldap' # ldap or ldaps
    ldap_hostname: 'ldap.novatech-llc.com'
    ldap_port: 389
    ldap_auth: 'simple'
    ldap_auth_username: 'cn=proxyagent,dc=novatech'
    ldap_auth_password: '{{ openldap_proxyagent_password }}'
    ldap_search_base: 'dc=novatech'
    ldap_user_base_dn: 'ou=user'
    #ldap_user_filter: '(cn=*)' # (optional)
    ldap_user_object_class: 'inetOrgPerson'
    ldap_user_id_attribute: 'uid'
    ldap_user_real_name_attribute: 'cn'
    ldap_user_email_attribute: 'mail'
    ldap_map_groups_as_roles: yes
    ldap_map_groups_as_roles_type: "static"
    ldap_user_memberof_attribute: ""
    ldap_group_base_dn: 'ou=group'
    ldap_group_object_class: 'posixGroup'
    ldap_group_id_attribute: 'cn'
    ldap_group_member_attribute: 'memberUid'
    ldap_group_member_format: '${username}'
    ldap_user_subtree: false
    ldap_group_subtree: true

nexus_anonymous_access: true

nexus_privileges:
  - name: all-repos-read  # used as key to update a privilege
    description: 'Read & Browse access to all repos'
    repository: '*'
    actions:
      - read
      - browse

nexus_roles:
  - id: anonymous
    name: anonymous
    description: Selective anonymous access
    privileges:
      - nx-repository-view-docker-docker-browse
      - nx-repository-view-docker-docker-read
      - nx-repository-view-pypi-pypi-browse
      - nx-repository-view-pypi-pypi-read
      - nx-repository-view-raw-debian-browse
      - nx-repository-view-raw-debian-read
      - nx-repository-view-raw-docs-browse
      - nx-repository-view-raw-docs-read
      - nx-repository-view-raw-download-browse
      - nx-repository-view-raw-download-read
      - nx-repository-view-raw-gnu-browse
      - nx-repository-view-raw-gnu-read
      - nx-repository-view-raw-kernel-browse
      - nx-repository-view-raw-kernel-read
      - nx-repository-view-raw-orphans-browse
      - nx-repository-view-raw-orphans-read
      - nx-repository-view-raw-public-releases-browse
      - nx-repository-view-raw-public-releases-read
      - nx-repository-view-raw-sourceforge-browse
      - nx-repository-view-raw-sourceforge-read
      - nx-repository-view-raw-ubuntu-archive-browse
      - nx-repository-view-raw-ubuntu-archive-read
      - nx-repository-view-raw-xorg-browse
      - nx-repository-view-raw-xorg-read
    roles: []
  - id: Backup  # can map to a LDAP group id, also used as a key to update a role
    name: backup
    description: Backup system
    privileges:
      - nx-tasks-read
      - nx-tasks-run
    roles: []
  - id: Developers  # can map to a LDAP group id, also used as a key to update a role
    name: developers
    description: All developers
    privileges:
      - nx-search-read
      - all-repos-read
      - nx-repository-view-*-*-*
    roles: []
  - id: nexus.novatech-llc.com  # can map to a LDAP group id, also used as a key to update a role
    name: novatech
    description: All developers
    privileges:
      - nx-component-upload
      - nx-repository-view-*-*-add
      - nx-repository-view-*-*-browse
      - nx-repository-view-*-*-read

nexus_local_users:
  - username: anonymous
    first_name: Anonymous
    last_name: User
    email: anonymous@example.org
    password: ""
    roles:
      - anonymous
  - username: bacula
    first_name: Bacula
    last_name: Backups
    email: bacula@novatech-llc.com
    password: "{{ nexus_bacula_password }}"
    roles:
      - Backup
  - username: buildbot # used as key to update
    first_name: NovaTech
    last_name: CI
    email: buildbot@novatech-llc.com
    password: "{{ nexus_buildbot_password }}"
    roles:
      - Developers # role ID here
  - username: bacula
    first_name: Bacula
    last_name: Backups
    email: bacula@novatech-llc.com
    password: "{{ nexus_bacula_password }}"
    roles:
      - Backup

nexus_delete_default_blobstore: false
nexus_blob_split: false     # True - blobstores per format

nexus_blobstores:
- name: permanent
  path: '{{ nexus_data_dir }}/blobs/permanent'

nexus_delete_default_repos: true

nexus_config_maven: false

nexus_config_docker: true
nexus_repos_docker_group:
  - name: docker
    http_port: "{{ nexus_docker_group_port }}"
    v1_enabled: True
    member_repos:
      - docker-hosted
      - docker-proxy
nexus_repos_docker_hosted:
  - name: docker-hosted
    http_port: "{{ nexus_docker_hosted_port }}"
    v1_enabled: True
nexus_repos_docker_proxy:
  - name: docker-proxy
    http_port: "{{ nexus_docker_proxy_port }}"
    v1_enabled: True
    index_type: "HUB"
    proxy_url: "https://registry-1.docker.io"
    use_nexus_certificates_to_access_index: false

nexus_config_pypi: true
nexus_repos_pypi_group:
  - name: pypi
    member_repos:
      - pypi-hosted
      - pypi-proxy
nexus_repos_pypi_hosted:
  - name: pypi-hosted
    write_policy: allow  # one of "allow", "allow_once" or "deny"
nexus_repos_pypi_proxy:
  - name: pypi-proxy
    remote_url: 'https://pypi.python.org/'

nexus_config_raw: true
nexus_repos_raw_group: []
nexus_repos_raw_hosted:
  - name: docs
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: permanent
  - name: download
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: permanent
  - name: ntel-release
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: permanent
  - name: ntel-sstate
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: default
  - name: ntel-unofficial
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: default
  - name: orphans
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: permanent
  - name: ptxdist-release
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: permanent
  - name: ptxdist-unofficial
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: default
  - name: public-releases
    strict_content_validation: false
    write_policy: allow  # one of "allow", "allow_once" or "deny"
    blob_store: permanent
nexus_repos_raw_proxy:
  - name: debian
    remote_url: 'http://ftp.us.debian.org/debian/'
    strict_content_validation: false
    blob_store: default
  - name: gnu
    remote_url: 'http://mirror.team-cymru.com/gnu/'
    strict_content_validation: false
    blob_store: default
  - name: kernel
    remote_url: 'https://mirrors.edge.kernel.org/pub/'
    strict_content_validation: false
    blob_store: default
  - name: sourceforge
    remote_url: 'http://downloads.sourceforge.net/project'
    strict_content_validation: false
    blob_store: default
  - name: ubuntu-archive
    remote_url: 'http://archive.ubuntu.com/ubuntu/'
    strict_content_validation: false
    blob_store: default
  - name: xorg
    remote_url: 'http://xorg.mirrors.pair.com/'
    strict_content_validation: false
    blob_store: default

nexus_config_rubygems: false
nexus_config_bower: false
nexus_config_npm: false
nexus_config_nuget: false
nexus_config_gitlfs: false
nexus_config_yum: false
