---
#=========================================================
# IPKG Data Container
#---------------------------------------------------------
- name: Build docker image ----- Test Station ipkg data
  docker_image:
    build:
      path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_http_data_ipkg.dir_name }}"
      pull: yes
    name: "{{ name_prefix }}teststation_http_data_ipkg_image"
    source: build
    state: "{{ image_build_state_data }}"
    force_source: "{{ docker_image_force_build }}"

- name: Start docker container - Test Station ipkg data
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_http_data_ipkg_image"
    name: "{{ name_prefix }}TestStation_http_data_ipkg"
    state: "{{ container_start_state_data }}"
