---
#=========================================================
# Database Data Container
#---------------------------------------------------------
- name: Build docker image ----- Test Station database data
  docker_image:
    build:
      path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_database_data.dir_name }}"
      pull: yes
    name: "{{ name_prefix }}teststation_database_data_image"
    source: build
    state: "{{ image_build_state_data }}"
    force_source: "{{ docker_image_force_build }}"

- name: Start docker container - Test Station database data
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_database_data_image"
    name: "{{ name_prefix }}TestStation_database_data"
    state: "{{ container_start_state_data }}"
