---

# The hostname passed as an envirnment variable into the container
mantisbt_ip_addr: '127.0.0.1'
mantisbt_hostname: mantis.example.com
mantisbt_port_args:
  - '80'
  - '443'

# database usernames and passwords
mantisbt_db_user: novatech

# must pass in the following variables
# mantisbt_db_root_password: ''
# mantisbt_db_password: ''

# the name of the image being duilt and used for the container
mantisbt_image_dir: '{{ docker_projects_dir }}/docker-mantisbt'
mantisbt_image_name: '{{ docker_registry_username }}/mantisbt'

mantisbt_db_image_name: 'mysql:5'

# the name of the container being started
mantisbt_container_name: '{{ docker_name_prefix }}mantisbt'

# the name of the container being started
mantisbt_db_container_name: '{{ docker_name_prefix }}mantisbt_db'

# the name of the mysql config volume used by the mantisbt container
mantisbt_db_cv_name: '{{ docker_name_prefix }}mantisbt_db_CV'

# the name of the mysql data-volume used by the mantisbt container
mantisbt_db_dv_name: '{{ docker_name_prefix }}mantisbt_db_DV'

# restore directories to temporarly store data being restored into docker containers
mantisbt_docker_backup_dir: '{{ docker_backup_dir }}/MANTISBT'
mantisbt_docker_restore_dir: '{{ bacula_dest }}{{ mantisbt_docker_backup_dir }}'

# Monitoring package for MantisBT
mantisbt_monitor_image_name: 'lusotycoon/apache-exporter:v0.8.0'
mantisbt_monitor_container_name: '{{ docker_name_prefix }}mantisbt_monitor'
mantisbt_monitor_scrape_uri: "http://{{ mantisbt_container_name }}/server-status?auto" #URI to apache stub status page. (default "http://localhost/server-status/?auto")
mantisbt_monitor_telemetry_address: ":9117" #Address on which to expose metrics. (default ":9117")
mantisbt_monitor_telemetry_endpoint: "/metrics" #Path under which to expose metrics. (default "/metrics")

# files restored from tape
mantisbt_database_backup_file: '/mantisbtdb.sql'
mantisbt_database_files_table_backup_file: '/mantisbtdb-files_table.sql'

# Network names
docker_network_frontend: 'frontend'

# the name of the sql database used by mantisbt
mantisbt_database_name: 'bugtracker'
