---
# defaults file for loki

loki_container: "loki"

loki_command:
  - -config.file="{{ loki_etc_dir }}/{{ loki_config_file }}"

loki_config_template: "loki.yaml.j2"

loki_env: {}

loki_hostname: "loki.local"

loki_image: "grafana/loki:latest"

loki_networks:
  - name: bridge

loki_port_args:
  - '{{ loki_port_listen | string }}'

loki_restart_policy: 'no'

loki_etc_volume: "/etc/loki"
loki_storage_volume: "loki-storage"
loki_volumes:
  - "{{ loki_etc_volume }}:{{ loki_etc_dir }}"
  - "{{ loki_storage_volume }}:{{ loki_storage_dir }}"

# Configuration Defaults

# The module to run Loki with.
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#configuration-file-reference
loki_target_config: "all"

# Enables authentication through the X-Scope-OrgID header
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#configuration-file-reference
loki_auth_enabled_config: "false"

# Configures Loki's behavior as an HTTP server
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#server_config
loki_server_config:
  http_listen_port: '{{ loki_port_listen }}'

# configures the Loki Distributor.
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#server_config
loki_distributor_config: {}

# configures the Loki Querier.
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#querier_config
loki_querier_config: {}

# configures how connections to ingesters operate
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#ingester_config
loki_ingester_client_config: {}

# configures Ingesters.
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#ingester_config
loki_ingester_config:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

# configures one of many possible stores for both the index and chunks
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#storage_config
loki_storage_config:
  boltdb:
    directory: "{{ loki_storage_dir }}/index"

  filesystem:
    directory: "{{ loki_storage_dir }}/chunks"

# configures how chunks will be cached and how long to wait before saving them to the backing store.
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#chunk_store_config
loki_chunk_store_config:
  max_look_back_period: 0s

# configures schemas from given dates.
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#schema_config
loki_schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

# configures global and per-tenant limits for ingesting logs
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#limits_config
loki_limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

# configures how the table manager operates
# https://github.com/grafana/loki/blob/v1.4.1/docs/configuration/README.md#table_manager_config
loki_table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
