---

- name: template - bacula-bootstrap-backup
  template:
    src: bacula-bootstrap-backup
    dest: '{{ bacula_scripts_bootstrap_backup }}'
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rx,o=rx'

- name: run bacula-bootstrap-backup
  command: '{{ bacula_scripts_bootstrap_backup }}'
  become: true
  become_user: bacula
  become_method: sudo

- name: Assemble dir for backup scripts
  file:
    path: '{{ bacula_scripts_assembly_dir }}'
    state: directory
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'

- name: Create before_backup script header
  template:
    src: before_backup_head.j2
    dest: '{{ bacula_scripts_assembly_dir }}/00.before_backup'
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

- name: Create before_backup script footer
  template:
    src: before_backup_foot.j2
    dest: '{{ bacula_scripts_assembly_dir }}/99.before_backup'
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

- name: Create after_backup script header
  template:
    src: after_backup_head.j2
    dest: '{{ bacula_scripts_assembly_dir }}/00.after_backup'
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

- name: Create after_backup script footer
  template:
    src: after_backup_foot.j2
    dest: '{{ bacula_scripts_assembly_dir }}/99.after_backup'
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

# *****************************************************************************
# Install selinux policies

- import_tasks: selinux-script-policy.yml
