---
# defaults file for buildbot-tls-certificates

buildbot_ca_dir: "/etc/buildbot-ca"
buildbot_ca_key: "{{ buildbot_ca_dir }}/ca.key"
buildbot_ca_csr: "{{ buildbot_ca_dir }}/ca.csr"
buildbot_ca_pem: "{{ buildbot_ca_dir }}/ca.pem"
buildbot_ca_fields:
  CN: ca.example.com
  C: US
  E: ca@example.com
  L: Example Locality
  O: Example Org
  OU: Example Dept.
  ST: Example State
  not_before: '20200101000000Z'
  not_after: '20300101000000Z'


buildbot_client_certificates:
  - dir: "/etc/buildbot-master"
    key: "/etc/buildbot-master/master.key"
    csr: "/etc/buildbot-master/master.csr"
    pem: "/etc/buildbot-master/master.pem"
    fields:
      CN: buildbot.example.com
      C: US
      E: buildbot@example.com
      L: Example Locality
      O: Example Org
      OU: Example Dept.
      ST: Example State
      not_before: '20200101000000Z'
      not_after: '20300101000000Z'
