---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker
    command: 'sh -c "while true; do sleep 10000; done"'
    override_command: true
    pre_build_image: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
verifier:
  name: ansible
