---
# Generate a certificate authority for signing client certificates

- name: Make sure the local dir {{ buildbot_ca_dir }} for ssl files exists
  file:
    mode: 0700
    path: '{{ buildbot_ca_dir }}'
    state: directory

- name: Generate ca key {{ buildbot_ca_key }}.
  openssl_privatekey:
    path: '{{ buildbot_ca_key }}'
    size: 8192
    type: RSA
    state: present

- name: Generate ca.csr {{ buildbot_ca_csr }}.
  openssl_csr:
    path: '{{ buildbot_ca_csr }}'
    privatekey_path: '{{ buildbot_ca_key }}'
    basic_constraints:
    - "CA:TRUE"
    CN: '{{ buildbot_ca_fields.CN | default(omit) }}'
    C: '{{ buildbot_ca_fields.C | default(omit) }}'
    E: '{{ buildbot_ca_fields.E | default(omit) }}'
    L: '{{ buildbot_ca_fields.L | default(omit) }}'
    O: '{{ buildbot_ca_fields.O | default(omit) }}'
    OU: '{{ buildbot_ca_fields.OU | default(omit) }}'
    ST: '{{ buildbot_ca_fields.ST | default(omit) }}'
    state: present

- name: Generate ca.pem {{ buildbot_ca_pem }}.
  openssl_certificate:
    csr_path: '{{ buildbot_ca_csr }}'
    path: '{{ buildbot_ca_pem }}'
    privatekey_path: '{{ buildbot_ca_key }}'
    provider: selfsigned
    selfsigned_not_before: '{{ buildbot_ca_fields.not_before | default(omit) }}'
    selfsigned_not_after: '{{ buildbot_ca_fields.not_after | default(omit) }}'
