---
# Generate a client certificate

- name: Make sure the local dir '{{ client_certificate_dir }}' for ssl files exists.
  file:
    mode: 0700
    path: '{{ client_certificate_dir }}'
    state: directory

- name: Generate server key {{ client_certificate_key }}.
  openssl_privatekey:
    path: '{{ client_certificate_key }}'
    size: 8192
    type: RSA
    state: present

- name: Generate server req {{ client_certificate_csr }}.
  openssl_csr:
    path: '{{ client_certificate_csr }}'
    privatekey_path: '{{ client_certificate_key }}'
    CN: '{{ client_certificate_fields.CN | default(omit) }}'
    C: '{{ client_certificate_fields.C | default(omit) }}'
    E: '{{ client_certificate_fields.E | default(omit) }}'
    L: '{{ client_certificate_fields.L | default(omit) }}'
    O: '{{ client_certificate_fields.O | default(omit) }}'
    OU: '{{ client_certificate_fields.OU | default(omit) }}'
    ST: '{{ client_certificate_fields.ST | default(omit) }}'
    state: present

- name: Generate server cert {{ client_certificate_pem }}.
  openssl_certificate:
    csr_path: '{{ client_certificate_csr }}'
    path: '{{ client_certificate_pem }}'
    privatekey_path: '{{ client_certificate_key }}'
    provider: ownca
    ownca_path: '{{ buildbot_ca_pem }}'
    ownca_privatekey_path: '{{ buildbot_ca_key }}'
    ownca_not_before: '{{ buildbot_ca_fields.not_before | default(omit) }}'
    ownca_not_after: '{{ buildbot_ca_fields.not_after | default(omit) }}'
