---

- name: Generate credentials
  hosts: localhost
  become: no
  vars_files:
    - vars.yml
  tasks:
    - name: "Generate Buildbot TLS certificates"
      include_role:
        name: buildbot-tls-certificates

- name: Prepare
  hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: "Update Apt Cache"
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: "Install Docker engine"
      include_role:
        name: "geerlingguy.docker"

    - name: "Install python pip"
      include_role:
        name: "geerlingguy.pip"
      vars:
        pip_package: python3-pip
        pip_executable: pip3
        pip_install_packages:
          - docker

    - name: Create worker configuration directory
      file:
        path: "/etc/buildbot-master/{{ item.module }}/buildbot_ci"
        state: directory
        owner: '1000'
        group: '1000'
      loop: '{{ buildbot_worker_configs }}'

    - name: Create worker configuration file
      template:
        src: "worker.py.j2"
        dest: "/etc/buildbot-master/{{ item.module }}/buildbot_ci/__init__.py"
        owner: '1000'
        group: '1000'
      vars:
        buildbot_worker_name: '{{ item.buildbot_worker_name }}'
        buildbot_worker_passwd: '{{ item.buildbot_worker_passwd }}'
      loop: '{{ buildbot_worker_configs }}'

    - name: "Install Buildbot master"
      include_role:
        name: buildbot-master
