---
asset_host: 'https://nexus.novatech-llc.com/repository/download/'
asset_pypi: 'https://nexus.novatech-llc.com/repository/pypi/'

buildbot_ca_creds: '{{ molecule_ephemeral_directory + "/buildbot-ca" }}'
buildbot_ca_dir: '{{ buildbot_ca_creds }}'
buildbot_ca_csr: '{{ buildbot_ca_creds + "/ca.csr" }}'
buildbot_ca_key: '{{ buildbot_ca_creds + "/ca.key" }}'
buildbot_ca_pem: '{{ buildbot_ca_creds + "/ca.pem" }}'
buildbot_ca_fields:
  common_name: ca.example.com
  country_name: US
  email_address: ca@example.com
  locality_name: Example Locality
  organization_name: Example Org
  organizational_unit_name: Example Dept.
  state_or_province_name: Example State

buildbot_creds: '{{ molecule_ephemeral_directory + "/buildbot-master" }}'
buildbot_sshkey: '{{ buildbot_creds }}/id_rsa'
buildbot_tlsca:  '{{ buildbot_ca_pem }}'
buildbot_tlscsr: '{{ buildbot_creds }}/server.csr'
buildbot_tlskey: '{{ buildbot_creds }}/server.key'
buildbot_tlspem: '{{ buildbot_creds }}/server.pem'

buildbot_ssh_clients:
  - dir: '{{ buildbot_creds }}'
    sshkey: '{{ buildbot_sshkey }}'
  - dir: '{{ buildbot_worker_creds }}'
    sshkey: '{{ buildbot_worker_sshkey }}'

# volumes mounted within the container
buildbot_volumes:
  - '{{ buildbot_volume_data }}:{{ buildbot_data_path }}:z'
  - '{{ buildbot_hostdir_config }}/buildbot.tac:{{ buildbot_tac_file }}:ro'
  - '{{ buildbot_hostdir_config }}/master.cfg:{{ buildbot_cfg_file }}:ro'
  - '{{ buildbot_hostdir_config }}/novatech.py:{{ buildbot_data_path }}/novatech.py'
  - '{{ buildbot_hostdir_config }}/{{ buildbot_sshkey }}:{{ buildbot_ssh_id_file }}:ro'
  - '{{ buildbot_hostdir_config }}/known_hosts:{{ buildbot_known_hosts }}:ro'
  - '{{ buildbot_hostdir_ssl }}:{{ buildbot_ssl_dir }}:ro'
  - '{{ buildbot_hostdir_config }}/worker_ntel_morty:{{ buildbot_data_path }}/worker_ntel_morty'
  - '{{ buildbot_hostdir_config }}/worker_ntel_sumo:{{ buildbot_data_path }}/worker_ntel_sumo'
  - '{{ buildbot_hostdir_config }}/worker_ntel_warrior:{{ buildbot_data_path }}/worker_ntel_warrior'

buildbot_worker_configs:
  - module: 'worker_ntel_morty'
    buildbot_worker_name: 'buildbot-worker-ntel-morty'
    buildbot_worker_passwd: 'pass'
  - module: 'worker_ntel_sumo'
    buildbot_worker_name: 'buildbot-worker-ntel-sumo'
    buildbot_worker_passwd: 'pass'
  - module: 'worker_ntel_warrior'
    buildbot_worker_name: 'buildbot-worker-ntel-warrior'
    buildbot_worker_passwd: 'pass'


buildbot_worker_creds: '{{ molecule_ephemeral_directory + "/buildbot-worker1" }}'
buildbot_worker_sshkey: '{{ buildbot_worker_creds }}/id_rsa'
buildbot_worker_tlsca:  '{{ buildbot_ca_pem }}'
buildbot_worker_tlscsr: '{{ buildbot_worker_creds }}/worker1.csr'
buildbot_worker_tlskey: '{{ buildbot_worker_creds }}/worker1.key'
buildbot_worker_tlspem: '{{ buildbot_worker_creds }}/worker1.pem'

buildbot_client_certificates:
  - dir: '{{ buildbot_creds }}'
    csr: '{{ buildbot_tlscsr }}'
    key: '{{ buildbot_tlskey }}'
    pem: '{{ buildbot_tlspem }}'
    fields:
      common_name: buildbot
      country_name: US
      email_address: buildbot@example.com
      locality_name: Example Locality
      organization_name: Example Org
      organizational_unit_name: Example Dept.
      state_or_province_name: Example State
  - dir: '{{ buildbot_worker_creds }}'
    csr: '{{ buildbot_worker_tlscsr }}'
    key: '{{ buildbot_worker_tlskey }}'
    pem: '{{ buildbot_worker_tlspem }}'
    fields:
      common_name: buildbot-worker1
      country_name: US
      email_address: buildbot.worker1@example.com
      locality_name: Example Locality
      organization_name: Example Org
      organizational_unit_name: Example Dept.
      state_or_province_name: Example State

buildbot_networks:
  - name: 'workers'
