---
# vars file for prometheus

prometheus_command:
- --config.file={{ prometheus_config_dir }}/{{ prometheus_config_file }}
- --storage.tsdb.path={{ prometheus_db_dir }}
- --storage.tsdb.retention.time={{ prometheus_storage_retention }}
- --storage.tsdb.retention.size={{ prometheus_storage_retention_size }}
- --web.console.libraries=/usr/share/prometheus/console_libraries
- --web.console.templates=/usr/share/prometheus/consoles
- --web.listen-address={{ prometheus_web_listen_address }}
- --web.external-url={{ prometheus_web_external_url }}
- '{{ prometheus_command_extra }}'

prometheus_config_dir: /etc/prometheus
prometheus_config_file: 'prometheus.yml'

prometheus_db_dir: /prometheus

prometheus_port: '9090'
prometheus_web_listen_address: "0.0.0.0:{{ prometheus_port }}"

prometheus_uid: '65534'
