---
supportsite_domains:
- name: 'novatech-llc.com'
  attributes:
    comment: "Novatech Automation Services"
    ttl: 300
    emailAddress: "ipadmin@stabletransit.com"
  records:
    # - "data": "23.253.56.181"
    #   "name": "test.novatech-llc.com"
    #   "ttl": 300
    #   "type": "A"
    # - "data": "23.253.56.181"
    #   "name": "novatech-llc.com"
    #   "ttl": 86400
    #   "type": "A"
    # - "data": "216.21.169.52"
    #   "name": "mail.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "A"
    # - "data": "23.253.56.181"
    #   "name": "ncdupdate.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "A"
    # - "data": "64.126.95.183"
    #   "name": "orion.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "A"
    # - "data": "216.21.169.52"
    #   "name": "server1.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "A"
    # - "data": "216.21.169.52"
    #   "name": "server2.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "A"
    # - "data": "23.253.56.181"
    #   "name": "www.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "A"
    # - "data": "autodiscover.outlook.com"
    #   "name": "autodiscover.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "CNAME"
    # - "data": "webdir.online.lync.com"
    #   "name": "lyncdiscover.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "CNAME"
    # - "data": "sipdir.online.lync.com"
    #   "name": "sip.novatech-llc.com"
    #   "ttl": 86400
    #   "type": "CNAME"
    # - "data": "269D36976331ECC4CD3AF63ED5EF7093.59E2224A858FF11476DA1577421F4605.9d00fac236.ssl.com"
    #   "name": "_867FBF3EA0D8AC592ADD22AE81B4086F.novatech-llc.com"
    #   "ttl": 300
    #   "type": "CNAME"
    # - "data": "novatechllc-com02b.mail.eo.outlook.com"
    #   "name": "novatech-llc.com"
    #   "priority": 10
    #   "ttl": 86400
    #   "type": "MX"
    # - "data": "ns1.slicehost.net"
    #   "name": "novatech-llc.com"
    #   "ttl": 300
    #   "type": "NS"
    # - "data": "ns2.slicehost.net"
    #   "name": "novatech-llc.com"
    #   "ttl": 300
    #   "type": "NS"
    # - "data": "ns3.slicehost.net"
    #   "name": "novatech-llc.com"
    #   "ttl": 300
    #   "type": "NS"
    # - "data": "1 5061 sipfed.online.lync.com"
    #   "name": "_sipfederationtls._tcp.novatech-llc.com"
    #   "priority": 100
    #   "ttl": 86400
    #   "type": "SRV"
    # - "data": "1 443 sipdir.online.lync.com"
    #   "name": "_sip._tls.novatech-llc.com"
    #   "priority": 100
    #   "ttl": 86400
    #   "type": "SRV"
    - data: "v=DKIM1; k=rsa; p={{ lookup('file', exim4_dkim_public_key) }}"
      name: "a._domainkey.novatech-llc.com"
      ttl: 300
      type: "TXT"
    - data: "v=DMARC1; p=none"
      name: "_dmarc.novatech-llc.com"
      ttl: 300
      type: "TXT"
    - data: "v=spf1 a:mail.novatech-llc.com include:spf.microsoftonline.com ~all"
      name: "novatech-llc.com"
      ttl: 86400
      type: "TXT"
