---

container_addr_map:
  svn:
    ip_addr: 172.16.0.111
    #ip_addr: 172.16.0.101
    hostname: svn.novatech-llc.com
    bridge_num: 1
  git:
    ip_addr: 172.16.0.102
    hostname: git.novatech-llc.com
    bridge_num: 2
  wiki:
    ip_addr: 172.16.0.103
    hostname: wiki.novatech-llc.com
    bridge_num: 3
  mantis:
    ip_addr: 172.16.0.104
    hostname: mantis.novatech-llc.com
  build:
    ip_addr: 172.16.0.105
    hostname: build.novatech-llc.com
  testssh:
    ip_addr: 172.16.0.106
    hostname: testssh.novatech-llc.com
  107:
    ip_addr: 172.16.0.107
    hostname: 107.novatech-llc.com
  ldap:
    ip_addr: 172.16.0.108
    hostname: ldap.novatech-llc.com
    bridge_num: 8
  phpldapadmin:
    ip_addr: 172.16.0.108
    hostname: ldap.novatech-llc.com
    bridge_num: 8
  phpmyadmin:
    ip_addr: 172.16.0.109
    hostname: phpmyadmin.novatech-llc.com
  freeipa:
    ip_addr: 172.16.0.110
    hostname: freeipa.novatech-llc.com

container_port_map:
  svn:
    port_args: '-p {{ container_addr_map.svn.ip_addr }}:80:80 -p {{ container_addr_map.svn.ip_addr }}:443:443'
  git:
    port_args: '-p {{ container_addr_map.git.ip_addr }}:80:80 -p {{ container_addr_map.git.ip_addr }}:443:443  -p {{ container_addr_map.git.ip_addr }}:22:22'
  wiki:
    port_args: '-p {{ container_addr_map.wiki.ip_addr }}:80:80 -p {{ container_addr_map.wiki.ip_addr }}:443:443'
  mantis:
    port_args: '-p {{ container_addr_map.mantis.ip_addr }}:80:80 -p {{ container_addr_map.mantis.ip_addr }}:443:443'
  build:
    port_args: '-p {{ container_addr_map.build.ip_addr }}:80:80 -p {{ container_addr_map.build.ip_addr }}:443:443'
  testssh:
    port_args: '-p {{ container_addr_map.testssh.ip_addr }}:2200:22'
  107:
    port_args: '-P'
  ldap:
    port_args: '-p {{ container_addr_map.ldap.ip_addr }}:389:389 -p {{ container_addr_map.ldap.ip_addr }}:636:636'
  phpldapadmin:
    port_args: '-p {{ container_addr_map.phpldapadmin.ip_addr }}:80:80 -p {{ container_addr_map.phpldapadmin.ip_addr }}:443:443'
  phpmyadmin:
    port_args: '-p {{ container_addr_map.phpmyadmin.ip_addr }}:80:80 -p {{ container_addr_map.phpmyadmin.ip_addr }}:443:443'
