---

ansible_host: 172.16.103.52
ansible_password: '{{ lookup("password", buildbot_worker_testorionlxm_creds + "/novatech@buildbot_worker_testorionlxm length=20") }}'
ansible_become_password: '{{ lookup("password", buildbot_worker_testorionlxm_creds + "/root@buildbot_worker_testorionlxm length=20") }}'

buildbot_testorion_name: '{{ buildbot_worker_testorionlxm }}'
buildbot_testorion_passwd: '{{ buildbot_worker_testorionlxm_passwd }}'
buildbot_testorion_sshkey: '{{ buildbot_worker_testorionlxm_sshkey }}'
buildbot_testorion_tlsca: '{{ buildbot_ca_pem }}'
buildbot_testorion_tlskey: '{{ buildbot_worker_testorionlxm_tlskey }}'
buildbot_testorion_tlspem: '{{ buildbot_worker_testorionlxm_tlspem }}'
