---
- name: Converge
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: "Include buildbot-worker-testorion"
      include_role:
        name: "buildbot-worker-testorion"
      vars:
        buildbot_testorion_name: '{{ buildbot_worker1 }}'
        buildbot_testorion_passwd: 'pass'
        buildbot_testorion_sshkey: '{{ buildbot_worker1_sshkey }}'
        buildbot_testorion_tlsca: '{{ buildbot_worker1_tlsca }}'
        buildbot_testorion_tlskey: '{{ buildbot_worker1_tlskey }}'
        buildbot_testorion_tlspem: '{{ buildbot_worker1_tlspem }}'
