---
- name: Prepare
  hosts: all
  become: true
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
    - docker
  tasks:
    - name: "Install Docker engine"
      include_role:
        name: "geerlingguy.docker"

    - name: "Install python pip"
      include_role:
        name: "geerlingguy.pip"
