---
- name: Check preconditions
  assert:
    that:
    - bacula_director_password is defined
    - bacula_monitor_password is defined
    - bacula_catalog_password is defined

- import_tasks: mariadb_setup.yml

- name: Install/setup Bacula Director
  yum:
    name:
    - bacula-mysql-9.4.4-1.el7
    state: present
  notify: "restart bacula-dir"

- name: Assemble dir for backup scripts
  file:
    path: '{{ bacula_scripts_assembly_dir }}'
    state: directory

- name: Create director script directory
  file:
    path: '{{ bacula_scriptdir }}'
    owner: bacula
    group: bacula
    seuser: system_u
    serole: object_r
    setype: bacula_exec_t
    state: directory

- name: Create director log directory
  file:
    path: '{{ bacula_log_dir }}'
    owner: bacula
    group: bacula
    seuser: system_u
    serole: object_r
    setype: bacula_log_t
    state: directory

- name: Create director pid directory
  file:
    path: '{{ bacula_pid_dir }}'
    owner: bacula
    group: bacula
    seuser: system_u
    serole: object_r
    setype: var_run_t
    state: directory

- name: Create bacula configuration directory
  file:
    path: '{{ bacula_director_config_dir }}'
    owner: bacula
    group: bacula
    seuser: system_u
    serole: object_r
    setype: bacula_etc_t
    state: directory

- name: Create bacula data directories
  file:
    path: '{{ item }}'
    owner: bacula
    group: bacula
    seuser: system_u
    serole: object_r
    setype: bacula_var_lib_t
    state: directory
  loop:
    - '{{ bacula_data_dir }}'
    - '{{ bacula_bootstrap_dir }}'
    - '{{ bacula_catalog_dir }}'
    - '{{ bacula_director_working_dir }}'
    - '{{ bacula_filestorage_dir }}'

- name: Configure Bacula Director
  template:
    src: bacula-dir.conf.j2
    dest: '{{ bacula_director_config_dir }}/bacula-dir.conf'
    owner: bacula
    group: bacula
    mode: 0640
  notify: "restart bacula-dir"

- name: Test Bacula Director configuration
  command: |
    {{ bacula_install_bindir }}/bacula-dir -t
    -c {{ bacula_director_config_dir }}/bacula-dir.conf
  changed_when: false

- name: Enable and start Bacula Director
  service:
    name: bacula-dir
    enabled: yes
    state: started
  register: bacula_director_service
