---
- name: Check preconditions
  assert:
    that:
    - bacula_director_password is defined
    - bacula_monitor_password is defined
    - mariadb_bacula_password is defined
- name: Install/setup Bacula Director
  yum:
    name:
    - bacula-director
    state: present
- name: Assemble dir for backup scripts
  file:
    path: /usr/libexec/bacula/backup-scripts
    state: directory
- name: Configure Bacula Director
  template:
    src: bacula-dir.conf.j2
    dest: '{{ bacula_director_config_dir }}/bacula-dir.conf'
    owner: bacula
    group: bacula
    mode: 0640
    backup: yes
  register: bacula_director_config_status
- name: Use libbaccats-mysql
  command: alternatives --set libbaccats.so /usr/lib64/libbaccats-mysql.so
- import_tasks: bacula-user.yml
- name: Check if bacula mysql database exists
  command: mysql -u root -e "SHOW DATABASES;"
  register: databases
- import_tasks: mariadb_setup.yml
  when: databases.stdout.find('bacula') == -1
- name: Test Bacula Director configuration
  command: /usr/sbin/bacula-dir -t -c {{ bacula_director_config_dir }}/bacula-dir.conf

- name: Set selinux port definitions for Bacula Director
  seport:
    ports: '{{ bacula_director_port }}'
    proto: tcp
    setype: bacula_port_t
    state: present

- name: Enable and restart Bacula Director
  service:
    name: bacula-dir
    enabled: yes
    state: restarted
  when: bacula_director_config_status.changed
- name: Enable and start Bacula Director
  service:
    name: bacula-dir
    enabled: yes
    state: started
  when: not bacula_director_config_status.changed
