---
- name: Use libbaccats-mysql
  alternatives:
    link: '{{ bacula_install_libdir }}/libbaccats.so'
    name: libbaccats.so
    path: '{{ bacula_install_libdir }}/libbaccats-mysql.so'

# - name: Flush mysql privileges
#   shell: mysql -u root -e "FLUSH PRIVILEGES;"

- name: Create bacula mysql database
  mysql_db:
    name: '{{ bacula_catalog_database }}'
    state: present

- name: Create bacula mysql user
  mysql_user:
    host_all: no
    name: '{{ bacula_catalog_user }}'
    password: '{{ bacula_catalog_password }}'
    priv: '{{ bacula_catalog_database }}.*:ALL'
    state: present
    update_password: always

- name: Make mysql tables
  command: >
    {{ bacula_install_scriptdir }}/make_mysql_tables
    -u root
