---
#=========================================================
# NCD Release Data Container
#---------------------------------------------------------
- name: Build docker image ----- Support Site ncd release data
  docker_image: 
    name: "{{ docker_name_prefix }}supportsite_http_data_ncdrelease_image"
    path: "{{ repo_destination }}/{{ supportsite_docker_repos.SupportSite_http_data_ncdrelease.dir_name }}"
    state: "{{ image_build_state_data }}"

- name: Start docker container - Support Site ncd release data
  docker: 
    detach: True
    image: "{{ docker_name_prefix }}supportsite_http_data_ncdrelease_image"
    name: "{{ docker_name_prefix }}SupportSite_http_data_ncdrelease"
    state: "{{ container_start_state_data }}"
